name: Staging deploy
on:
  workflow_dispatch:

jobs: 
  build: 
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: sohost
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
